"""Display text used by the Streamlit UI."""

UI_TEXT = {
    "en": {
        "theme": "Theme",
        "light": "Light",
        "dark": "Dark",
        "run_setup": "Run setup",
        "upload_title": "Upload GenBank files",
        "upload_body": (
            "Use one well-annotated reference record and one query file containing "
            "one or more genomes. ViraLift will detect the virus alias config, "
            "choose direct extraction or tblastn per record, then ask only for "
            "gene-name decisions it cannot resolve."
        ),
        "reference_record": "Reference record",
        "reference_caption": "Single annotated GenBank file",
        "query_records": "Query records",
        "query_caption": "One or many genomes in GenBank format",
        "file_requirements": "File requirements",
        "file_requirements_body": (
            "- Reference file: exactly one GenBank record with usable CDS or mat_peptide annotations.\n"
            "- Query file: one or more GenBank records; annotations are optional.\n"
            "- Supported extensions: `.gb` and `.gbk`.\n"
            "- Alias config is auto-detected from `app/config/virus_alias_registry.json`."
        ),
        "advanced_options": "Advanced options",
        "lifting_thresholds": "Lifting thresholds",
        "threshold_caption": "Defaults are permissive for divergent viral genomes. Tighten them when you want higher-confidence extraction.",
        "min_coverage": "Min coverage",
        "min_identity": "Min identity",
        "evalue": "E-value",
        "rescue_window": "Rescue window",
        "use_ref_names": "Use ref gene names as output",
        "use_ref_names_help": (
            "OFF (default): output canonical names from the alias config key (e.g. 'Lpro').\n\n"
            "ON: output the ref's original gene name instead (e.g. 'Lab' if that's what the ref says)."
        ),
        "run_button": "Run ViraLift",
        "loading_files": "Loading files...",
        "load_error": "We could not load these files",
        "reference_file": "Reference file",
        "query_file": "Query file",
        "name_mode": "Name mode",
        "reference_names": "reference names",
        "canonical_names": "canonical names",
        "alias_review": "Alias review",
        "resolve_title": "Resolve gene names",
        "resolve_body": (
            "ViraLift found names that are not cleanly covered by the alias database. "
            "Map only the names you trust; excluded names are skipped from automatic alias matching."
        ),
        "reference": "Reference",
        "detected_virus": "Detected virus",
        "alias_keys": "Alias keys",
        "ref_missing_title": "{count} ref gene(s) not in alias DB. Review",
        "ref_missing_body": (
            "These names from the **reference** were not found in the **{virus}** alias config. "
            "Lifting still works (tblastn uses protein sequence, not the name), but they will appear "
            "in output with their **raw annotation name** instead of a canonical key.\n\n"
            "You can add them as new canonical entries now so they're recognised in future runs, or just continue as-is."
        ),
        "unrecognised_ref_names": "Unrecognised ref names:",
        "add_canonical": "Add **`{name}`** as a new canonical to alias config",
        "add_canonical_help": "Creates a new entry '{name}: []' in the alias config. You can add aliases to it later by editing the JSON file.",
        "save_ref_names": "Save selected ref names to alias config",
        "canonicals_added": "{count} new canonical(s) added to alias config",
        "already_exists": "All selected names already exist in the config.",
        "unknown_query_intro": "The query file contains **{count} unrecognised name(s)** not found in the **{virus}** alias config. Decide what to do with each one before running.",
        "all_known": "All query gene names are already in the alias config. No query-side decisions needed.",
        "ignore_option": "-- exclude / keep raw name --",
        "ambiguous_prefix": "Excluded",
        "unknown_prefix": "Unknown",
        "appears_in": "Appears in",
        "map_to_canonical": "Map to canonical",
        "save": "Save",
        "save_aliases": "Save aliases",
        "save_candidate_help": "Add only this candidate value to the alias config so it is recognised next time.",
        "ambiguous_intro": "**{count} excluded name(s)**. These names are configured to be skipped during automatic alias matching in **{virus}**. Select a canonical only if this dataset provides enough context.",
        "back": "Back",
        "continue": "Continue with these decisions",
        "aliases_saved": "{count} alias(es) saved to config",
        "processing": "Processing",
        "running_title": "Running ViraLift",
        "running_body": "Each query record is routed independently. Records that fail are logged and shown in the results review.",
        "starting": "Starting...",
        "done": "Done.",
        "run_review": "Run review",
        "results_title": "Results",
        "results_body": "Review run health first, then inspect records that need attention before exporting TSV or FASTA.",
        "ref_names_caption": "Names shown as ref gene names. Start a new run to use canonical keys.",
        "new_run": "New run",
        "records_processed": "Records processed",
        "features_found": "Features found",
        "pass_rate": "Pass rate",
        "needs_review": "Needs review",
        "failed_delta": "{count} failed",
        "processing_error": "{count} query record(s) failed during processing. They are excluded from pass-rate calculations and listed below.",
        "processing_errors": "Processing errors",
        "status_breakdown": "Status breakdown",
        "record_overview": "Record overview",
        "health_filter": "Health filter",
        "all": "all",
        "yes": "yes",
        "no": "no",
        "search_record": "Search record ID",
        "open_all": "Open all details",
        "record_details": "Record details",
        "failed": "Failed",
        "empty": "Empty",
        "passed": "Passed",
        "no_features": "No features were returned for this record.",
        "export": "Export",
        "tsv": "TSV",
        "fasta": "FASTA extraction",
        "download_table": "Download the full results table.",
        "download_display": "Download TSV (display names)",
        "download_raw": "Download TSV (raw/source names)",
        "fasta_intro": "Select genes and quality filters before generating FASTA downloads.",
        "genes_to_extract": "Genes to extract",
        "output_format": "Output format",
        "one_fasta": "One FASTA per gene",
        "all_fasta": "All genes in one FASTA",
        "quality_filter": "Quality filter",
        "include_rescued": "Include ok_rescued",
        "include_extrapolated": "Include ok_extrapolated",
        "manual_approve_features": "Manually approve individual review features",
        "manual_approve_help": "Optional. Export only the selected review cases after you inspect them. Approved cases bypass status and quality filters.",
        "approve_for_fasta": "Approve selected for FASTA export",
        "approved_for_fasta": "Approved for FASTA export",
        "clear_approved_for_record": "Clear approvals in this record",
        "approved_export_count": "{count} manually approved review feature(s) will be included in FASTA export.",
        "candidate_count": "{count} sequence(s) currently pass these FASTA filters.",
        "generate_fasta": "Generate FASTA downloads",
        "download_all_fasta": "Download all_genes.fasta",
        "no_sequences": "No sequences for `{gene}` passed the filter.",
        "gene_download": "{gene}.fasta  ({count} sequences)",
        "skipped": "{count} features skipped due to quality filter or missing sequence.",
        "stage_files": "1 Files",
        "stage_setup": "2 Virus & aliases",
        "stage_name_review": "3 Name review",
        "stage_run_annotation": "4 Run annotation",
        "stage_results": "5 Results",
        "stage_upload": "Files",
        "stage_virus_review": "Virus & aliases",
        "stage_bootstrap": "Virus & aliases",
        "stage_resolve": "Name review",
        "stage_run": "Run annotation",
        "stage_review": "Results",
        "sidebar_subtitle": "Reference-guided viral gene name standardisation",
        "alias_config": "Alias config",
        "stage": "Stage",
        "loaded": "{count} loaded",
        "status_ok": "OK",
        "status_ok_rescued": "Rescued",
        "status_direct": "Direct",
        "status_invalid_boundaries": "Invalid boundary",
        "status_low_coverage": "Low coverage",
        "status_low_identity": "Low identity",
        "status_low_coverage_and_identity": "Low coverage + identity",
        "status_no_hit": "No hit",
        "status_translation_fail": "Translation fail",
        "status_unresolved_name": "Unresolved name",
        "status_ambiguous_name": "Excluded name",
        "status_not_in_reference": "Not in reference",
        "tone_pass": "PASS",
        "tone_review": "REVIEW",
        "tone_fail": "FAIL",
    },
}
